name: Deploy to DEV

on:
  push:
    branches: [ dev ]
    # tags:
    #   - '*.dev'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Create tag and build docker image
        run: npm run deploy
        env:
          DEPLOY_ENV: dev

      - name: Get the version
        id: get_version
        run: |
          git fetch --tags --unshallow
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Get tag
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}